version: '3.8'
services:
  api:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    networks:
      - bridge_network
  redis:
    image: redis:latest
    networks:
      - bridge_network
networks:
  bridge_network:
    driver: bridge
